/*
 * ======================================================================================
 * Module : 		UltraSonic
 * File Name : 	 	ultrasonic.h
 * Description :	Ultrasonic Driver Source File
 * Author : 	 	Mostafa Medhat
 * ======================================================================================
 */

#include "ultrasonic.h"
#include "common_macros.h"
#include "icu.h"
#include "util/delay.h"


uint8 g_edgeCount = 0;
uint16 g_echoTime = 0;


/*
 * Description :
 * Initialize the ICU driver.
 * Setup the ICU call back function.
 * Setup the direction for the trigger pin as output pin through the GPIO driver
 */

void Ultrasonic_init(void)
{
	/*
	 * The ICU should be configured with frequency F_CPU/8 and to detect the raising edge as the first edge.
	 */
	Icu_ConfigType Icu_Config = {F_CPU_8,RISING};
	Icu_init(&Icu_Config);
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, PIN_OUTPUT);
	/* Write Logic LOW on the trigger pin */
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN,LOGIC_LOW);

}

/*
 * Description :
 * This Function is used to send the Trigger pulse to the ultrasonic.
 */

void Ultrasonic_Trigger(void)
{
	/*
	 * Send Trigger pulse by writing logic High on this pin and wait for at least 10ns so that
	 * the sensor sends 40khz wave and waits for rising edge output at the Echo pin.
	 * When the rising edge capture occurs at the Echo pin which is connected to an input of ATmega16,
	 * start Timer of ATmega16 and again wait for a falling edge on the Echo pin.
	 */
		GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN,LOGIC_HIGH);
		_delay_us(ULTRASONIC_TRIGGER_DELAY);
		GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN,LOGIC_LOW);
}

/*
 * Description :
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */

void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_echoTime = Icu_getInputCaptureValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
		/* Clear the timer counter register to start measurements again */
		Icu_clearTimerValue();
		g_edgeCount=0;
	}
}


/*
 * Description :
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void)
{
	Ultrasonic_Trigger();		//Call ultrasonic trigger function to begin the measurement of the distance
	/*
	 *  Sound velocity = 340.00 m/s = 34000 cm/s
		The distance of Object (in cm) = (340000/2)*Time = 17000 * Time

		Now, here we have selected an internal 8MHz oscillator frequency for ATmega16, with
		Prescaler F_CPU/8 for timer frequency. Then time to execute 1 instruction is 1 us.
		So, the timer gets incremented after 1 us time elapse.

		= 17000 x (TIMER value) x 1 x 10^-6 cm ... to convert time to from micro-seconds to seconds
		= 0.017 x (TIMER value) cm
		= (TIMER value) / 58.8 cm
	 */
	return (g_echoTime/58);
}






